services:
  mkdocs:
    container_name: mkdocs
    restart: always
    build: .
    develop:
      watch:
        - action: sync
          path: docs
          target: /flare-docs/docs
        - action: rebuild
          path: requirements.txt
    ports:
      - "8000:8000"
    environment:
      LIVE_RELOAD_SUPPORT: 'true'