name: Docker Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build MkDocs Site
        run: |
          docker run --rm -v ${{ github.workspace }}:/docs squidfunk/mkdocs-material build --strict